# NAME: SHEN TENG
# EMAIL: REDHAIRDRAGON@UCLA.EDU
# ID: 104758168
default:
	
clean:
	rm -r lab3b-104758168.tar.gz 
dist:
	tar -czf lab3b-104758168.tar.gz Blocks.py BlocksInfo.py DirectoryInfo.py FileImg.py Inode.py InodesInfo.py Makefile SuperBlock.py lab3b README