# NAME: SHEN TENG
# EMAIL: REDHAIRDRAGON@UCLA.EDU
# ID: 104758168
build:
	gcc lab4b.c -lmraa -lm -o lab4b
clean:
	rm -f lab4b log lab4b-104758168.tar.gz
check:
	make
	(sleep 3 &&	echo "OFF" )|	./lab4b
dist:
	tar -zcf lab4b-104758168.tar.gz Makefile lab4b.c README
