# NAME: SHEN TENG
# EMAIL: REDHAIRDRAGON@UCLA.EDU
# ID: 104758168
build:
	gcc lab3a.c -o lab3a -lm
clean:
	rm -f lab3a lab3a-104758168.tar.gz 
dist:
	tar -czvf lab3a-104758168.tar.gz lab3a.c README Makefile ext2_fs.h 
