# NAME: SHEN TENG
# EMAIL: REDHAIRDRAGON@UCLA.EDU
# ID: 104758168
build:
	gcc lab4c_tcp.c -lmraa -lm -o lab4c_tcp
	gcc lab4c_tls.c -lmraa -lm -lssl -lcrypto -o lab4c_tls
clean:
	rm -f lab4c_tcp lab4c_tls lab4c-104758168.tar.gz
dist:
	tar -zcf lab4c-104758168.tar.gz Makefile lab4c_tcp.c lab4c_tls.c README
